name: Auto Approval Check

on:
  deployment_status:
  
#jobs:
#  on_deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Auto Approve Deployment
#        if: github.event.deployment_status.state == 'waiting'
#        uses: ambilykk/deployment-auto-approve@main
#        with:
#         GITHUB_TOKEN: ${{ secrets.PAT }}   
#         environment: ${{ github.event.deployment.environment }}
       

#on:
#  deployment:
#    types: [created]

jobs:
  auto-approve:
    if: github.event.deployment_status.state == 'waiting'
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      actions: write
      contents: read

    steps:
      - name: Only run if deployment is queued (waiting for approval)
        if: ${{ github.event.deployment_status.state != 'queued' }}
        run: |
          echo "Deployment is not waiting; skipping workflow."
          exit 0

      - name: Extract environment & actor
        id: vars
        run: |
          echo "env_name=${{ github.event.deployment.environment }}" >> $GITHUB_OUTPUT
          echo "actor=${{ github.actor }}" >> $GITHUB_OUTPUT
          echo "deployment_id=${{ github.event.deployment.id }}" >> $GITHUB_OUTPUT
          echo "sha=${{ github.event.deployment.sha }}" >> $GITHUB_OUTPUT

      - name: Get environment reviewers (users + teams safely)
        id: reviewers
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          REPO: ${{ github.repository }}
          ENV_NAME: ${{ steps.vars.outputs.env_name }}
        run: |
          # Fetch environment JSON; fallback to empty object
          env_json=$(gh api repos/$REPO/environments/$ENV_NAME 2>/dev/null || echo '{}')

          # Individual users
          users=$(echo "$env_json" | jq -r '.reviewers // [] | .[] | select(.type=="User") | .reviewer.login')

          # Team reviewers
          teams=$(echo "$env_json" | jq -r '.reviewers // [] | .[] | select(.type=="Team") | .reviewer.slug')

          # Expand team members
          members=""
          for team in $teams; do
            team_members=$(gh api repos/$REPO/teams/$team/members --jq '.[].login' || true)
            members="$members $team_members"
          done

          # Combine all reviewers
          all_reviewers="$users $members"

          echo "reviewers=$all_reviewers" >> $GITHUB_OUTPUT
          echo "Allowed reviewers: $all_reviewers"

      - name: Check if actor is in reviewer list
        id: check
        run: |
          actor="${{ steps.vars.outputs.actor }}"
          reviewers="${{ steps.reviewers.outputs.reviewers }}"

          echo "Deployment actor: $actor"
          if echo "$reviewers" | grep -qw "$actor"; then
            echo "is_approved=true" >> $GITHUB_OUTPUT
          else
            echo "is_approved=false" >> $GITHUB_OUTPUT
          fi

      - name: Approve deployment
        if: steps.check.outputs.is_approved == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          DEPLOYMENT_ID: ${{ steps.vars.outputs.deployment_id }}
        run: |
          echo "Approving deployment $DEPLOYMENT_ID for $REPO"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            repos/$REPO/deployments/$DEPLOYMENT_ID/statuses \
            -f state=success

      - name: Add job summary
        run: |
          echo "## Deployment Auto-Approval Result" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Environment:** ${{ steps.vars.outputs.env_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Deployment Actor:** ${{ steps.vars.outputs.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "**Deployment SHA:** ${{ steps.vars.outputs.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "**Deployment ID:** ${{ steps.vars.outputs.deployment_id }}" >> $GITHUB_STEP_SUMMARY
          echo "**Allowed Reviewers:** ${{ steps.reviewers.outputs.reviewers }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ steps.check.outputs.is_approved }}" == "true" ]]; then
            echo "✅ Deployment was auto-approved." >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ Deployment was NOT auto-approved (actor not in reviewers list)." >> $GITHUB_STEP_SUMMARY
          fi
   
