name: Run Mongo Shell Migration
on:
  workflow_dispatch:
    inputs:
      target_env:
       required: true
       description: 'Target Environment'
       type: choice
       options:
         - stage
      script_file:
       required: true
       description: 'Script File'
       type: string
  
jobs:
  migrate:
    uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Run-MongoDB-Migration.yml@main
    with:
      working_directory: 'ngo-nabarun-be/ngo-nabarun-app/migrate'
      script_file: ${{ inputs.script_file }}
      source_db: ${{ inputs.target_env == 'prod' && 'nabarun_stage' || 'nabarun_prod3' }}
      dest_db: ${{ inputs.target_env == 'prod' && 'nabarun_prod3' || 'nabarun_stage' }}
      environment_name: ${{ inputs.target_env }}
      repository_name: 'nabarun-ngo/ngo-nabarun-be'
      branch_name: ${{ inputs.target_env == 'prod' && 'master' || 'stage' }}
    secrets:
      MONGO_URI: ${{ secrets.APP_MONGODB_URI }}
